apiVersion: v1
kind: Pod
metadata:
  name: kafkagroup
  labels:
    name: kafkagroup
spec:
  containers:
  - name: fast-data-dev
    image: landoop/fast-data-dev
    ports:
      - containerPort: 9092
      - containerPort: 2181
      - containerPort: 8081
      - containerPort: 8082
      - containerPort: 8083
      - containerPort: 9581
      - containerPort: 9582
      - containerPort: 9584
      - containerPort: 9585
      - containerPort: 3030
    env:
      - name: DISABLE
        value: azure-documentdb,bloomberg,druid,hazelcast,hbase,jms,kudu,mqtt,voltdb,yahoo,hdfs,elasticsearch,twitter
      - name: CONNECT_HEAP
        value: 1024m
      - name: ADV_HOST
        value: kafka
      - name: RUNNING_SAMPLEDATA
        value: "1"
    resources:
      requests:
        memory: "2.8Gi"
      limits:
        memory: "3.6Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: fast-data-dev-ui
spec:
  type: NodePort
  ports:
    - port: 3030
  selector:
    name: kafkagroup
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: broker-jmx
    port: 9581
    targetPort: 9581
  - name: schema-registry
    port: 8081
    targetPort: 8081
  - name: schema-registry-jmx
    port: 9582
    targetPort: 9582
  - name: kafka-rest
    port: 8082
    targetPort: 8082
  - name: kafka-rest-jmx
    port: 9583
    targetPort: 9583
  - name: connect
    port: 8083
    targetPort: 8083
  - name: connect-jmx
    port: 9584
    targetPort: 9584
  - name: zookeeper
    port: 2181
    targetPort: 2181
  - name: zookeeper-jmx
    port: 9585
    targetPort: 9585
  selector:
    name: kafkagroup
