apiVersion: v1
kind: Pod
metadata:
  name: lenses
  labels:
    name: lenses
spec:
  containers:
  - name: lenses-runtime
    image: landoop/lenses:latest
    # imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 9991
    env:
      - name: LENSES_PORT
        value: "9991"
      - name: LENSES_JMX_PORT
        value: "9015"
      - name: LENSES_KAFKA_BROKERS
        value: PLAINTEXT://kafka:9092
      - name: LENSES_ZOOKEEPER_HOSTS
        value: kafka:2181
      - name: LENSES_SCHEMA_REGISTRY_URLS
        value: http://kafka:8081
      - name: LENSES_CONNECT
        value: '[{default: "http://kafka:8083"}]'
      - name: LENSES_JMX_BROKERS
        value: kafka:9581
      - name: LENSES_JMX_SCHEMA_REGISTRY
        value: kafka:9582
      - name: LENSES_JMX_CONNECT
        value: '[{default: "kafka:9584"}]'
      - name: LENSES_JMX_ZOOKEEPERS
        value: kafka:9585
      - name: LENSES_SECURITY_MODE
        value: BASIC
      - name: LENSES_HEAP_OPTS
        value: "-Xmx1G"
    volumeMounts:
    - name: lenses-secrets
      mountPath: "/mnt/secrets/"
      readOnly: true
    resources:
      requests:
        memory: "750Mi"
      limits:
        memory: "1.2Gi"
  volumes:
  - name: lenses-secrets
    secret:
      secretName: lenses-secrets
      defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: lenses
spec:
  type: NodePort
  ports:
    - port: 9991
  selector:
    name: lenses
