#!/usr/bin/env bash
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
# Source commit not yet (?) supported by docker hub.
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"
export BUILD_COMMIT="$(git rev-parse HEAD)"
echo "BUILD_COMMIT: ${BUILD_COMMIT}"
export BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "BUILD_TIME: ${BUILD_TIME}"
echo "DOCKER_REPO: ${DOCKER_REPO}"

# Load build information
LENSES_BASE_VERSION=$(grep "ARG LENSES_BASE_VERSION=" Dockerfile | cut -d'=' -f2)
LENSES_PATCH_VERSION=$(grep "ARG LENSES_PATCH_VERSION=" Dockerfile | cut -d'=' -f2)
LENSES_VERSION=${LENSES_BASE_VERSION}.${LENSES_PATCH_VERSION}

if [[ -z $SOURCE_BRANCH ]]; then
    if [[ -z $GIT_BRANCH ]]; then
        echo "GIT_BRANCH not set"
        exit 1
    fi
    echo "SOURCE_BRANCH not set. Setting it to GIT_BRANCH: $GIT_BRANCH"
    export SOURCE_BRANCH=$GIT_BRANCH
fi

# Set the tags (image names) for this build

# Deprecated, for agent we will start clean and publish only lensesio/lenses-agent
# ## Default image name (landoop/lenses:ATAG)
# TAGS_CMD="--tag $IMAGE_NAME"
# TAGS_CMD_DEBIAN="--tag $IMAGE_NAME-debian"
TAGS_CMD=""
TAGS_CMD_DEBIAN=""

## Master should lensesio/lenses-agent:latest, lensesio/lenses-agent:latest-debian
if [[ $SOURCE_BRANCH == master ]]; then
    # 'landooop/lenses:latest' is pushed automatically
    TAGS_CMD="$TAGS_CMD --tag lensesio/lenses-agent:latest"
    TAGS_CMD_DEBIAN="$TAGS_CMD_DEBIAN --tag lensesio/lenses-agent:latest-debian"
fi

# Branches should publish minor (patch) and major (minor) version tags
if [[ $SOURCE_BRANCH =~ ^release/[0-9]+\.[0-9]+$ ]] \
       && [[ -n $LENSES_VERSION ]] \
       && [[ -n $LENSES_BASE_VERSION ]]; then
    # Push 'lensesio/lenses:$LENSES_BASE_VERSION'
    TAGS_CMD="$TAGS_CMD --tag lensesio/lenses-agent:$LENSES_BASE_VERSION"
    TAGS_CMD_DEBIAN="$TAGS_CMD_DEBIAN --tag lensesio/lenses-agent:$LENSES_BASE_VERSION-debian"

    # Also push 'lensesio/lenses:$MINOR_VERSION'
    TAGS_CMD="$TAGS_CMD --tag lensesio/lenses-agent:$LENSES_VERSION"
    TAGS_CMD_DEBIAN="$TAGS_CMD_DEBIAN --tag lensesio/lenses-agent:$LENSES_VERSION-debian"
fi

# Build and push the images
docker buildx create \
       --name mybuilder \
       --driver docker-container \
       --bootstrap \
       --use
## Standard images
docker buildx build \
       --platform=linux/amd64,linux/arm64 \
       --push \
       --build-arg "BUILD_BRANCH=${SOURCE_BRANCH}" \
       --build-arg "BUILD_COMMIT=${BUILD_COMMIT}" \
       --build-arg "BUILD_TIME=${BUILD_TIME}" \
       --build-arg "DOCKER_REPO=${DOCKER_REPO}" \
       ${TAGS_CMD} \
       .
## Debian images
docker buildx build \
       --platform=linux/amd64,linux/arm64 \
       --push \
       --build-arg "BUILD_BRANCH=${SOURCE_BRANCH}" \
       --build-arg "BUILD_COMMIT=${BUILD_COMMIT}" \
       --build-arg "BUILD_TIME=${BUILD_TIME}" \
       --build-arg "DOCKER_REPO=${DOCKER_REPO}" \
       --target lenses_debian \
       ${TAGS_CMD_DEBIAN} \
       .
